import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import 'hammerjs';

import {
  MatButtonModule,
  MatInputModule,
  MatCheckboxModule,
  MatGridListModule,
  MatCardModule,
  MatIconModule,
  MatSidenavModule,
  MatMenuModule,
  MatToolbarModule,
  MatTabsModule,
  MatListModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatSelectModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatTooltipModule,
  MatChipsModule,
  MatRadioModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatProgressBarModule,
  MatAutocompleteModule,
  MatDialogModule,
  MatExpansionModule,
  MatButtonToggleModule,
  MatDividerModule,
  MatProgressSpinnerModule,
  MatRippleModule,
  MatSliderModule,
  MatStepperModule
} from '@angular/material'; 

@NgModule({
  exports: [
    MatButtonModule,
    MatInputModule,
    MatCheckboxModule,
    MatGridListModule,
    MatCardModule,
    MatIconModule,
    MatSidenavModule,
    MatMenuModule,
    MatToolbarModule,
    MatTabsModule,
    MatListModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatTooltipModule,
    MatChipsModule,
    MatRadioModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatDividerModule,
    MatProgressSpinnerModule,
    MatRippleModule,
    MatSliderModule,
    MatStepperModule,
    FormsModule, ReactiveFormsModule
  ],
})
export class MaterialModule { }
